### PR TITLE
Added travis ci support for modern node versions

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by kriskowal** [comment]
Let’s keep 0.10. There’s an awful lot of that in production systems. I’m adding you as a collaborator so you can manage this yourself.

**Comment by amilajack** [comment]
Thanks! Added it back. Do you also mind if I updated the readme to es6?

**Comment by kriskowal** [comment]
@amilajack I’d be fine with adding a section describing the ES6 equivalent syntax. The future is not distributed evenly.

**Comment by amilajack** [comment]
Sounds good!

**Pull request merged**
